---
include:
  - board: eyelash_corne_left
    shield: nice_view
    #snippet: zmk-usb-logging    # Uncomment to log over USB.
  - board: eyelash_corne_left
    shield: nice_view
    #snippet: zmk-usb-logging    # Uncomment to log over USB.Add commentMore actions
  - board: eyelash_corne_right
    shield: nice_view
    #snippet: zmk-usb-logging
